/// Flutter icons AppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'icons';
  static const String? _kFontPkg = null;

  static const IconData icon_mocktest = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_clock = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_learn = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_lock = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_logout = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_question = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_star = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_user = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hazmat = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_home = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_war = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pen = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData term = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arithmetic = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assembling = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData auto_shop = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electronics = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData school = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mathematics = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mechanical = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paragraph = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData word = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multi_star = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_calendar = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_rate = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_aim = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_menu = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData passenger = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pre_trip = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tanker = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData combination = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorcycle = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cdl = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData practice = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData integrated = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData select_course = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytical = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verbal = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quantitative = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logical = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytical_1 = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData studyplan = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toeic_practice_test = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toeic_grammar = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toeic_vocabulary = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashcards = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytical_2 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verbal_1 = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quant_ = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag_report = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData function = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physical = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData psychosocial = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roles = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifi_icon = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData process = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anatomy = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData people_1 = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biology = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chemistry = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grammar = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mathematics_1 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physics = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reading = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vocabulary = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airway = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardio = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ems = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashcards_1 = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medical = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trauma = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData extra = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData core = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData benefits = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData client = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethics = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guidelines = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kinesiology = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pathology = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alternative = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corporate = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData derivatives = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData economics = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equity = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethical = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData financial = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fixed = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portfolio = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quantitative_1 = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_fill_color = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email_fill_color = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifi = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speaking = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData practice_1 = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_1 = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifi_icon_1 = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_fill_color = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_fill_color = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData record = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting_1 = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calender = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_lock_1 = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dowload_file = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downlload_file = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData finsh = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData listen = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sound = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData turnoff_mic = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terms = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_account = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy_1 = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_1 = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_ielts = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xf00c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
